config/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import HomeView, AsyncView

from master.api_urls import api_urlpatterns

# 通常 Url定義
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('account/', include('allauth.urls')),
    path('master/', include('master.urls')),
    path('api/1.0/', include(api_urlpatterns)),
]

master/urls.py
from django.urls import path, include

from .views import TopView
from .views import SampleView
from .views import EmployeeListView, EmployeeCreateView, EmployeeUpdateView, EmployeeDeleteView
from .views import GradeListView, GradeCreateView, GradeUpdateView, GradeDeleteView
from .views import PositionListView, PositionCreateView, PositionUpdateView, PositionDeleteView
from .views import DepartmentListView, DepartmentCreateView, DepartmentUpdateView, DepartmentDeleteView
from .views import AffiliationListView, AffiliationCreateView, AffiliationUpdateView, AffiliationDeleteView
from .views import AccountingPeriodListView, AccountingPeriodCreateView, AccountingPeriodUpdateView, AccountingPeriodDeleteView
from .views import CostListView, CostCreateView, CostUpdateView, CostDeleteView
from .views import ClientListView, ClientCreateView, ClientUpdateView, ClientDeleteView
from .views import PartnerListView, PartnerCreateView, PartnerUpdateView, PartnerDeleteView

urlpatterns = [

    # top
    path('', TopView.as_view(), name='master.top'),
    path('sample', SampleView.as_view(), name='master.sample'),
 
    # employee
    path('employee/index', EmployeeListView.as_view(), name='master.employee.index'),
    path('employee/create', EmployeeCreateView.as_view(), name='master.employee.create'),
    path('employee/update/<int:pk>/', EmployeeUpdateView.as_view(), name='master.employee.update'),
    path('employee/delete/<int:pk>/', EmployeeDeleteView.as_view(), name='master.employee.delete'),
 
    # grade
    path('grade/index', GradeListView.as_view(), name='master.grade.index'),
    path('grade/create', GradeCreateView.as_view(), name='master.grade.create'),
    path('grade/update/<str:pk>/', GradeUpdateView.as_view(), name='master.grade.update'),
    path('grade/delete/<str:pk>/', GradeDeleteView.as_view(), name='master.grade.delete'),
 
    # position
    path('position/index', PositionListView.as_view(), name='master.position.index'),
    path('position/create', PositionCreateView.as_view(), name='master.position.create'),
    path('position/update/<str:pk>/', PositionUpdateView.as_view(), name='master.position.update'),
    path('position/delete/<str:pk>/', PositionDeleteView.as_view(), name='master.position.delete'),
 
    # department
    path('department/index', DepartmentListView.as_view(), name='master.department.index'),
    path('department/create', DepartmentCreateView.as_view(), name='master.department.create'),
    path('department/update/<str:pk>/', DepartmentUpdateView.as_view(), name='master.department.update'),
    path('department/delete/<str:pk>/', DepartmentDeleteView.as_view(), name='master.department.delete'),
 
    # affiliation
    path('affiliation/index', AffiliationListView.as_view(), name='master.affiliation.index'),
    path('affiliation/create', AffiliationCreateView.as_view(), name='master.affiliation.create'),
    path('affiliation/update/<int:pk>/', AffiliationUpdateView.as_view(), name='master.affiliation.update'),
    path('affiliation/delete/<int:pk>/', AffiliationDeleteView.as_view(), name='master.affiliation.delete'),

    # accounting_period
    path('accounting_period/index', AccountingPeriodListView.as_view(), name='master.accounting_period.index'),
    path('accounting_period/create', AccountingPeriodCreateView.as_view(), name='master.accounting_period.create'),
    path('accounting_period/update/<int:pk>/', AccountingPeriodUpdateView.as_view(), name='master.accounting_period.update'),
    path('accounting_period/delete/<int:pk>/', AccountingPeriodDeleteView.as_view(), name='master.accounting_period.delete'),

    # cost
    path('cost/index', CostListView.as_view(), name='master.cost.index'),
    path('cost/create', CostCreateView.as_view(), name='master.cost.create'),
    path('cost/update/<int:pk>/', CostUpdateView.as_view(), name='master.cost.update'),
    path('cost/delete/<int:pk>/', CostDeleteView.as_view(), name='master.cost.delete'),

    # client
    path('client/index', ClientListView.as_view(), name='master.client.index'),
    path('client/create', ClientCreateView.as_view(), name='master.client.create'),
    path('client/update/<int:pk>/', ClientUpdateView.as_view(), name='master.client.update'),
    path('client/delete/<int:pk>/', ClientDeleteView.as_view(), name='master.client.delete'),

    # partner
    path('partner/index', PartnerListView.as_view(), name='master.partner.index'),
    path('partner/create', PartnerCreateView.as_view(), name='master.partner.create'),
    path('partner/update/<int:pk>/', PartnerUpdateView.as_view(), name='master.partner.update'),
    path('partner/delete/<int:pk>/', PartnerDeleteView.as_view(), name='master.partner.delete'),
]

master/models/affiliation.py
from django.db import models

from .department import Department
from .grade import Grade
from .position import Position
from .employee import Employee
from .accounting_period import AccountingPeriod

# Create your models here.

# 所属マスタテーブル
class Affiliation(models.Model):
    accounting_period = models.ForeignKey(AccountingPeriod, on_delete=models.SET_NULL, null=True, verbose_name="会計期")
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, null=True, verbose_name="部門")
    position = models.ForeignKey(Position, on_delete=models.SET_NULL, null=True, verbose_name="役職")
    grade = models.ForeignKey(Grade, on_delete=models.SET_NULL, null=True, verbose_name="資格")
    employee = models.ForeignKey(Employee, on_delete=models.SET_NULL, null=True, verbose_name="氏名")
    updated = models.DateTimeField(verbose_name="更新日時", auto_now=True)
    created = models.DateTimeField(verbose_name="登録日時", auto_now_add=True)

    class Meta:
        verbose_name_plural = '所属マスター'
        ordering = ['department__display_order', 'position__display_order', 'grade__display_order']

    def __str__(self):
        return str(self.accounting_period) + ' : ' + str(self.department) + ' : ' + str(self.employee)

master/forms/accounting_period.py
from django import forms

from ..models.accounting_period import AccountingPeriod

class AccountingPeriodForm(forms.ModelForm):
    class Meta:
        model = AccountingPeriod
        fields = '__all__'
        widgets = {
            'start_date': forms.NumberInput(attrs={ "type": "date" }),
            'end_date': forms.NumberInput(attrs={ "type": "date" }),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

class AccountingPeriodSearchForm(forms.Form):
    keyword = forms.fields.CharField(
        label = 'キーワード検索',
        required = False,
        widget=forms.widgets.TextInput,
    )

class AccountingPeriodImportForm(forms.Form):
    upload_file = forms.fields.FileField(
        label = 'アップロードファイル',
        required = True,
        widget=forms.widgets.FileInput,
    )

master/forms/affiliation.py
from django import forms

from ..models.affiliation import Affiliation
from ..models.accounting_period import AccountingPeriod

class AffiliationForm(forms.ModelForm):
    class Meta:
        model = Affiliation
        fields = '__all__'
        widgets = {
            'start_date': forms.NumberInput(attrs={ "type": "date" }),
            'end_date': forms.NumberInput(attrs={ "type": "date" }),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

class AffiliationSearchForm(forms.Form):
    search_accounting_period = forms.ModelChoiceField(
        queryset=AccountingPeriod.objects.all(),
        label = '会計期',
        required = False,
    )
    keyword = forms.fields.CharField(
        label = 'キーワード検索',
        required = False,
        widget=forms.widgets.TextInput,
    )

class AffiliationImportForm(forms.Form):
    upload_file = forms.fields.FileField(
        label = 'アップロードファイル',
        required = True,
        widget=forms.widgets.FileInput,
    )

master/forms/client.py
from django import forms

from ..models.client import Client

class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = '__all__'
        widgets = {
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

class ClientSearchForm(forms.Form):
    keyword = forms.fields.CharField(
        label = 'キーワード検索',
        required = False,
        widget=forms.widgets.TextInput,
    )

class ClientImportForm(forms.Form):
    upload_file = forms.fields.FileField(
        label = 'アップロードファイル',
        required = True,
        widget=forms.widgets.FileInput,
    )

master/forms/cost.py
from django import forms

from ..models.cost import Cost
from ..models.accounting_period import AccountingPeriod
from ..models.employee import Employee

class CostForm(forms.ModelForm):
    class Meta:
        model = Cost
        fields = '__all__'
        widgets = {
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

class CostSearchForm(forms.Form):
    search_accounting_period = forms.ModelChoiceField(
        queryset=AccountingPeriod.objects.all(),
        label = '会計期',
        required = False,
    )
    keyword = forms.fields.CharField(
        label = 'キーワード検索',
        required = False,
        widget=forms.widgets.TextInput,
    )

class CostImportForm(forms.Form):
    search_accounting_period = forms.ModelChoiceField(
        queryset=AccountingPeriod.objects.all(),
        label = '会計期',
        required = True,
    )
    upload_file = forms.fields.FileField(
        label = 'アップロードファイル',
        required = True,
        widget=forms.widgets.FileInput,
    )

master/forms/department.py
from django import forms

from ..models.department import Department

class DepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = '__all__'
        widgets = {
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #self.fields['retirement_date'].disabled = True

class DepartmentSearchForm(forms.Form):
    keyword = forms.fields.CharField(
        label = 'キーワード検索',
        required = False,
        widget=forms.widgets.TextInput,
    )

class DepartmentImportForm(forms.Form):
    upload_file = forms.fields.FileField(
        label = 'アップロードファイル',
        required = True,
        widget=forms.widgets.FileInput,
    )

master/forms/employee.py
from django import forms

from ..models.employee import Employee

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'
        widgets = {
            'date_of_birth': forms.NumberInput(attrs={ "type": "date" }),
            'hire_date': forms.NumberInput(attrs={ "type": "date" }),
            'retirement_date': forms.NumberInput(attrs={ "type": "date" }),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

class EmployeeSearchForm(forms.Form):
    keyword = forms.fields.CharField(
        label = 'キーワード検索',
        required = False,
        widget=forms.widgets.TextInput,
    )

class EmployeeImportForm(forms.Form):
    upload_file = forms.fields.FileField(
        label = 'アップロードファイル',
        required = True,
        widget=forms.widgets.FileInput,
    )

master/views/accounting_period.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView, FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.utils import timezone
import openpyxl
from datetime import datetime
from django.db.models import Q

from master.models import AccountingPeriod
from master.forms import AccountingPeriodForm, AccountingPeriodSearchForm, AccountingPeriodImportForm
from . import BaseView

class AccountingPeriodListView(LoginRequiredMixin, ListView, BaseView):
    template_name = 'master/accounting_period/index.html'
    model = AccountingPeriod
    paginate_by = 10
    context_object_name = 'items'

    def get_queryset(self):

        # param = 'init' の場合 セッションクリア
        if self.request.GET.get('param', '') == 'init':
            if 'accounting_period_search_values' in self.request.session:
                del self.request.session['accounting_period_search_values']

        # sessionに値がある場合、その値でクエリ発行する。
        if 'accounting_period_search_values' in self.request.session:

            # セッションから検索情報取得
            search_values = self.request.session['accounting_period_search_values']

            # 検索条件
            condition1 = Q()

            # 検索文字が指定されている場合、条件設定
            if len(search_values) != 0:
                condition1 = Q(accounting_period__icontains=search_values[0])

            # 検索条件を指定して検索結果取得
            return AccountingPeriod.objects.select_related().filter(condition1)

        else:
            # 検索条件指定なしの場合、全件取得
            return AccountingPeriod.objects.all()

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)

        # sessionに値がある場合、その値をセットする。（ページングしてもform値が変わらないように）
        if 'accounting_period_search_values' in self.request.session:
            search_values = self.request.session['accounting_period_search_values']
            default_data = {
                'keyword': search_values[0],
            }
        else:
            default_data = {
                'keyword': '',
            }

        context['search_form'] = AccountingPeriodSearchForm(initial=default_data)
        context['import_form'] = AccountingPeriodImportForm()

        return context

    def post(self, request, *args, **kwargs):

        try:
            # アップロード時
            if self.request.POST.get('mode', '') == 'upload':

                upload_file = self.request.FILES['upload_file']

                # 役職ファイルアプロード処理
                if not self.import_accounting_period(upload_file):
                    print('import_accounting_period Error !!')

            # 検索時
            elif self.request.POST.get('mode', '') == 'search':

                # セッションに検索値を設定
                search_values = [
                    self.request.POST.get('keyword', ''),
                ]
                request.session['accounting_period_search_values'] = search_values

        except Exception as e:
            print(e)

        finally:
            # 検索時にページネーションに関連したエラーを防ぐ
            self.request.GET = self.request.GET.copy()
            self.request.GET.clear()
            return self.get(request, *args, **kwargs)

    def import_accounting_period(self, upload_file):

        try:
            # アップロードファイルのオープン
            wb = openpyxl.load_workbook(upload_file, data_only=True)

            # 先頭シートを参照
            ws = wb.worksheets[0]

            # 一括追加用配列
            insert_items = []
            update_items = []

            i = 2
            while i <= ws.max_row:

                # 会計期と氏名が同じデータ取得
                result = AccountingPeriod.objects.filter(accounting_period=int(ws.cell(row=i, column=1).value))

                # 同じデータ存在確認
                if not result.exists():

                    # 存在しない場合、新規登録
                    item = AccountingPeriod(
                        accounting_period = ws.cell(row=i, column=1).value,
                        start_date = self.convert_string_to_date(ws.cell(row=i, column=2).value, None),
                        end_date = self.convert_string_to_date(ws.cell(row=i, column=3).value, None),
                    )

                    insert_items.append(item)
                else:
                    # 存在する場合、更新
                    item = result.get()
                    
                    item.start_date = self.convert_string_to_date(ws.cell(row=i, column=2).value, None)
                    item.end_date = self.convert_string_to_date(ws.cell(row=i, column=3).value, None)
                    item.updated = datetime.now()

                    update_items.append(item)

                i = i + 1

            # 更新リストデータが存在する場合
            if len(update_items) > 0:
                AccountingPeriod.objects.bulk_update(update_items, ['start_date','end_date','updated'])

            # 新規リストデータが存在する場合
            if len(insert_items) > 0:
                AccountingPeriod.objects.bulk_create(insert_items)

            wb.close()
            rc = True

        except Exception as e:
            print(e)
            rc = False

        return rc

class AccountingPeriodCreateView(LoginRequiredMixin, CreateView):
    template_name = 'master/accounting_period/create.html'
    model = AccountingPeriod
    form_class = AccountingPeriodForm
    success_url = reverse_lazy('master.accounting_period.index')

class AccountingPeriodUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'master/accounting_period/update.html'
    model = AccountingPeriod
    form_class = AccountingPeriodForm
    success_url = reverse_lazy('master.accounting_period.index')
    context_object_name = 'item'

    def form_valid(self, form):
        Affiliation = form.save(commit=False)
        Affiliation.updated = timezone.now()
        Affiliation.save()
        return super().form_valid(form)

class AccountingPeriodDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'master/accounting_period/delete.html'
    model = AccountingPeriod
    success_url = reverse_lazy('master.accounting_period.index')
    context_object_name = 'item'

templates/master/accounting_period/create.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% load bootstrap_icons %}

{% block head_title %}会計期間情報 登録{% endblock %}

{% block content %}
<div class="container-fluid p-4 small">
  <div class="row">
    <div class="col-2"></div>
    <div class="col">
      <form method="POST">
        <div class="row mb-3">
          <div class="col-6">
            <h4>会計期間情報 新規登録</h4>
          </div>
          <div class="col-6 text-end">
            <button type="submit" class="btn btn-primary btn-md">
              <i class="fa-solid fa-floppy-disk"></i> 登録
            </button>
            <a href="{% url 'master.accounting_period.index' %}" class="btn btn-secondary btn-md">
              <i class="fa-solid fa-ban"></i> キャンセル
            </a>
          </div>
        </div>
        {% csrf_token %}
        {% bootstrap_form form layout='floating' alert_error_type='fields' %}
        <button type="submit" class="btn btn-primary btn-md">
          <i class="fa-solid fa-floppy-disk"></i> 登録
        </button>
        <a href="{% url 'master.accounting_period.index' %}" class="btn btn-secondary btn-md">
          <i class="fa-solid fa-ban"></i> キャンセル
        </a>
      </form>
    </div>
    <div class="col-2"></div>
  </div>
</div>
{% endblock %}

templates/master/accounting_period/delete.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% load bootstrap_icons %}
{% load humanize %}

{% block head_title %}会計期間情報 削除{% endblock %}

{% block content %}
<div class="container-fluid p-4 small">
  <div class="row">
    <div class="col-2"></div>
    <div class="col">
      <h4 class="mb-3">会計期間情報 削除</h4>
      <div class="alert alert-danger" role="alert">
        以下のデータを削除してもよろしいですか？
      </div>
      <form method="POST">
        {% csrf_token %}
        <div class="mb-3 form-floating">
          <input type="text" value="{{ item.accounting_period }}" class="form-control" disabled readonly>
          <label class="form-label">会計期</label>
        </div>
        <div class="mb-3 form-floating">
          <input type="text" value="{{ item.start_date|date:'Y/m/d' }}" class="form-control" disabled readonly>
          <label class="form-label">開始日</label>
        </div>
        <div class="mb-3 form-floating">
          <input type="text" value="{{ item.end_date|date:'Y/m/d' }}" class="form-control" disabled readonly>
          <label class="form-label">終了日</label>
        </div>
        <div class="mb-3 form-floating">
          <input type="text" value='{{ item.created|date:"Y/m/d H:i:s" }}' class="form-control" disabled readonly>
          <label class="form-label">登録日時</label>
        </div>
        <div class="mb-3 form-floating">
          <input type="text" value='{{ item.updated|date:"Y/m/d H:i:s" }}' class="form-control" disabled readonly>
          <label class="form-label">更新日時</label>
        </div>
        {% bootstrap_button button_type="submit" content="はい" size="md" button_class="btn btn-danger" %}
        <a href="{% url 'master.accounting_period.index' %}" class="btn btn-secondary btn-md my-3">いいえ</a>
      </form>
    </div>
    <div class="col-2"></div>
  </div>
</div>
{% endblock %}

templates/master/accounting_period/index.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% load bootstrap_icons %}
{% load i18n %}
{% load humanize %}

{% block head_title %}会計期間マスタ{% endblock %}

{% block content %}
<div class="container-fluid p-4 small">
    {% include 'common/list_view_title_block.html' with title='会計期間一覧' search=True upload=True append=True create_url='master.accounting_period.create' %}
    <div class="row">
        {% if items|length == 0 %}
        <div class="col-8 offset-2">
            <div class="alert alert-warning" role="alert">
                検索結果が存在しません。
            </div>
        </div>
        {% else %}
        <table class="table table-hover table-striped table-bordered table-sm small">
            <thead class="table-light text-center">
                <tr>
                <th scope="col">会計期</th>
                <th scope="col">開始日</th>
                <th scope="col">終了日</th>
                <th scope="col">タイトル</th>
                <th scope="col">登録日時</th>
                <th scope="col">更新日時</th>
                <th>　</th>
                </tr>
            </thead>
            <tbody class="align-middle">
            {% for item in items %}
                <tr>
                    <td class="text-center">{{ item.get_accounting_period_display }}</td>
                    <td class="text-center">{{ item.start_date|date:"Y/m/d" }}</td>
                    <td class="text-center">{{ item.end_date|date:"Y/m/d" }}</td>
                    <td>{{ item.get_accounting_period_title }}</td>
                    <td class="text-center">{{ item.created|date:"Y/m/d H:i:s" }}</td>
                    <td class="text-center">{{ item.updated|date:"Y/m/d H:i:s" }}</td>
                    <td class="text-center">
                        <a href="{% url 'master.accounting_period.update' item.pk %}" class="btn btn-sm">
                            <i class="fa-solid fa-pen-to-square"></i>
                        </a>
                        <a href="{% url 'master.accounting_period.delete' item.pk %}" class="btn btn-sm">
                            <i class="fa-solid fa-trash-can"></i>
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="pagination justify-content-center">
            {% bootstrap_pagination page_obj %}
        </div>
        {% endif %}
    </div>
    {% include 'common/import_dialog_modal.html' %}
    {% include 'common/search_dialog_modal.html' %}
</div>
{% endblock %}

templates/master/accounting_period/update.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% load bootstrap_icons %}
{% load humanize %}

{% block head_title %}会計期間情報 編集{% endblock %}

{% block content %}
<div class="container-fluid p-4 small">
  <div class="row">
    <div class="col-2"></div>
    <div class="col">
      <form method="POST">
        <div class="row mb-3">
          <div class="col-6">
            <h4>会計期間情報 編集</h4>
          </div>
          <div class="col-6 text-end">
            <button type="submit" class="btn btn-primary btn-md">
              <i class="fa-solid fa-floppy-disk"></i> 保存
            </button>
            <a href="{% url 'master.accounting_period.index' %}" class="btn btn-secondary btn-md">
              <i class="fa-solid fa-ban"></i> キャンセル
            </a>
          </div>
        </div>
        {% csrf_token %}
        {% bootstrap_form form layout='floating' %}
        <div class="mb-3 form-floating">
          <input type="text" value='{{ item.created|date:"Y/m/d H:i:s" }}' class="form-control" disabled readonly>
          <label class="form-label">登録日時</label>
        </div>
        <div class="mb-3 form-floating">
          <input type="text" value='{{ item.updated|date:"Y/m/d H:i:s" }}' class="form-control" disabled readonly>
          <label class="form-label">更新日時</label>
        </div>
        <button type="submit" class="btn btn-primary btn-md">
          <i class="fa-solid fa-floppy-disk"></i> 保存
        </button>
        <a href="{% url 'master.accounting_period.index' %}" class="btn btn-secondary btn-md">
          <i class="fa-solid fa-ban"></i> キャンセル
        </a>
      </form>
    </div>
    <div class="col-2"></div>
  </div>
</div>
{% endblock %}